# 应用名称
spring:
  application:
    name: service-verification-code
  redis:
    host: 192.168.33.104
    port: 6379


server:
  port: 8082
  #是否注册到注册中心
eureka:
  client:
    enabled: true
    service-url:
        # defaultZone :  http://localhost:7900/eureka, http://localhost:7901/eureka, http://localhost:7902/eureka
       defaultZone:  http://localhost:7900/eureka

