
spring:
  datasource:
    local:
      username: root
      password: root
    #  driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    remote:
      username: root
      password: 123456
  #    driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.33.104:3306/test?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.msb.entity